---
title: "Data Preprocessing/Analysis: of LUX AVG & GHI from 18-05"
author: "by Jawad Haider"
format: 
  html: 
    toc: true
    toc-name: Contents
link-external-newwindow: true
html-math-method: katex
anchor-sections: true
smooth-scroll: true
link-external-icon: true
jupyter: python3
comments:
  hypothesis: 
    theme: clean
reference-location: margin
---

# Import the libraries

In [ ]:
import pandas as pd
import natsort
from natsort import natsorted

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Lux datasets from day18-25
***Note: The data for day 20 is missing***

In [ ]:
#TRAININGSDATA 18-12-2023 - 01.01.2023

#/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_data/     GHI/LUX

lux18=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-18.csv")
lux19=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-19.csv")
lux21=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-21.csv")
lux22=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-22.csv")
lux23=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-23.csv")
lux24=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-24.csv")
lux25=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-25.csv")
lux26=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-26.csv")
lux27=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-27.csv")
lux28=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-28.csv")
lux29=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-29.csv")
lux30=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-30.csv")
lux31=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2022-12-31.csv")
lux01=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2023-01-01.csv")
lux05=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/LUX_SERIES/ExposureSeriesLux-data-as-joinbyfield-2023-01-05.csv")
lux05.head()

,Time,Lux4 Regression,Lux6 Regression,Lux3 Regression,Lux7 Regression,Lux0 Regression,Lux8 Regression,Lux2 Regression,Lux1 Regression,Lux5 Regression
0,2023-01-05 08:13:00,827,477,1343,414,400,392,2388,3583,519
1,2023-01-05 08:14:00,827,479,1343,422,400,400,2388,3583,519
2,2023-01-05 08:15:00,827,502,1343,457,400,425,2388,3583,529
3,2023-01-05 08:16:00,832,544,1343,503,400,468,2388,3583,580
4,2023-01-05 08:17:00,832,569,1343,529,400,497,2388,3583,617

In [ ]:
lux18 = lux18.reindex(columns=natsort.natsorted(lux05.columns))
lux19 = lux19.reindex(columns=natsort.natsorted(lux05.columns))
lux21 = lux21.reindex(columns=natsort.natsorted(lux05.columns))
lux22 = lux22.reindex(columns=natsort.natsorted(lux05.columns))
lux24 = lux24.reindex(columns=natsort.natsorted(lux05.columns))
lux25 = lux25.reindex(columns=natsort.natsorted(lux05.columns))
lux26 = lux26.reindex(columns=natsort.natsorted(lux05.columns))
lux27 = lux27.reindex(columns=natsort.natsorted(lux05.columns))
lux28 = lux28.reindex(columns=natsort.natsorted(lux05.columns))
lux29 = lux29.reindex(columns=natsort.natsorted(lux05.columns))
lux30 = lux30.reindex(columns=natsort.natsorted(lux05.columns))
lux31 = lux31.reindex(columns=natsort.natsorted(lux05.columns))
lux01 = lux01.reindex(columns=natsort.natsorted(lux05.columns))
lux05 = lux05.reindex(columns=natsort.natsorted(lux05.columns))
lux05

,Lux0 Regression,Lux1 Regression,Lux2 Regression,Lux3 Regression,Lux4 Regression,Lux5 Regression,Lux6 Regression,Lux7 Regression,Lux8 Regression,Time
0,400,3583,2388,1343,827,519,477,414,392,2023-01-05 08:13:00
1,400,3583,2388,1343,827,519,479,422,400,2023-01-05 08:14:00
2,400,3583,2388,1343,827,529,502,457,425,2023-01-05 08:15:00
3,400,3583,2388,1343,832,580,544,503,468,2023-01-05 08:16:00
4,400,3583,2388,1343,832,617,569,529,497,2023-01-05 08:17:00
...,...,...,...,...,...,...,...,...,...,...
476,400,3583,2388,1343,827,618,502,467,445,2023-01-05 16:09:00
477,400,3583,2388,1343,827,625,527,485,461,2023-01-05 16:10:00
478,400,3583,2388,1343,827,629,526,483,459,2023-01-05 16:11:00
479,400,3583,2388,1343,827,592,509,457,437,2023-01-05 16:12:00
480,400,3583,2388,1343,827,539,485,426,400,2023-01-05 16:13:00

# Varifying the columns
Checking if the data columns are different

In [ ]:
print(f"Columns for 18 = {lux05.columns}")

Columns for 18 = Index(['Lux0 Regression', 'Lux1 Regression', 'Lux2 Regression',
       'Lux3 Regression', 'Lux4 Regression', 'Lux5 Regression',
       'Lux6 Regression', 'Lux7 Regression', 'Lux8 Regression', 'Time'],
      dtype='object')

# Ghi datasets from day18-25
***Note again: The data for day 20 is missing***

In [ ]:
ghi18=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-18.csv")
ghi19=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-19.csv")
ghi21=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-21.csv")
ghi22=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-22.csv")
ghi23=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-23.csv")
ghi24=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-24.csv")
ghi25=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-25.csv")
ghi26=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-26.csv")
ghi27=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-27.csv")
ghi28=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-28.csv")
ghi29=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-29.csv")
ghi30=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-30.csv")
ghi31=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2022-12-31.csv")
ghi01=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2023-01-01.csv")
ghi05=pd.read_csv("/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/GHI/GHI-data-2023-01-05.csv")
ghi05

                    Time        GHI
0    2023-01-05 08:13:00  2.25 W/m²
1    2023-01-05 08:14:00  2.39 W/m²
2    2023-01-05 08:15:00  2.38 W/m²
3    2023-01-05 08:16:00  2.51 W/m²
4    2023-01-05 08:17:00  2.70 W/m²
..                   ...        ...
476  2023-01-05 16:09:00  2.88 W/m²
477  2023-01-05 16:10:00  2.57 W/m²
478  2023-01-05 16:11:00  3.11 W/m²
479  2023-01-05 16:12:00  3.02 W/m²
480  2023-01-05 16:13:00  2.81 W/m²

[481 rows x 2 columns]

# Varifying the columns

In [ ]:
print(f"Columns for ghi 18 ={ghi18.columns}")

Columns for ghi 18 =Index(['Time', 'GHI'], dtype='object')

In [ ]:
# checking the columns of each day 
print(f" lux 18 ={len(lux18)} ghi 18 ={len(ghi18)}")
print(f" lux 19 ={len(lux19)} ghi 19 ={len(ghi19)}")
print(f" lux 21 ={len(lux21)} ghi 21 ={len(ghi21)}")
print(f" lux 22 ={len(lux22)} ghi 22 ={len(ghi22)}")
print(f" lux 23 ={len(lux23)} ghi 23 ={len(ghi23)}")
print(f" lux 24 ={len(lux24)} ghi 24 ={len(ghi24)}")
print(f" lux 25 ={len(lux25)} ghi 25 ={len(ghi25)}")
print(f" lux 26 ={len(lux26)} ghi 26 ={len(ghi26)}")
print(f" lux 27 ={len(lux27)} ghi 27 ={len(ghi27)}")
print(f" lux 28 ={len(lux28)} ghi 28 ={len(ghi28)}")
print(f" lux 29 ={len(lux29)} ghi 29 ={len(ghi29)}")
print(f" lux 30 ={len(lux30)} ghi 30 ={len(ghi30)}")
print(f" lux 31 ={len(lux31)} ghi 31 ={len(ghi31)}")
print(f" lux 01 ={len(lux01)} ghi 01 ={len(ghi01)}")
print(f" lux 05 ={len(lux05)} ghi 05 ={len(ghi05)}")

 lux 18 =737 ghi 18 =737
 lux 19 =708 ghi 19 =708
 lux 21 =681 ghi 21 =681
 lux 22 =665 ghi 22 =665
 lux 23 =606 ghi 23 =606
 lux 24 =678 ghi 24 =678
 lux 25 =663 ghi 25 =663
 lux 26 =460 ghi 26 =460
 lux 27 =460 ghi 27 =460
 lux 28 =459 ghi 28 =459
 lux 29 =763 ghi 29 =763
 lux 30 =460 ghi 30 =460
 lux 31 =460 ghi 31 =460
 lux 01 =460 ghi 01 =460
 lux 05 =481 ghi 05 =481

# Getting the data ready to concatination

In [ ]:
'''
# As the rows for each day are different, we will use the minimum rows and ignore the other to avoid null values
# checking size to match
lux18=lux18.iloc[:737,:]
ghi18=ghi18.iloc[:737,:]

lux19=lux19.iloc[:708,:]
ghi19=ghi19.iloc[:708,:]

lux21=lux21.iloc[:681,:]
ghi21=ghi21.iloc[:681,:]

lux22=lux22.iloc[:665,:]
ghi22=ghi22.iloc[:665,:]

lux23=lux23.iloc[:606,:]
ghi23=ghi23.iloc[:606,:]

lux24=lux24.iloc[:678,:]
ghi24=ghi24.iloc[:678,:]

lux25=lux25.iloc[:663,:]
ghi25=ghi25.iloc[:663,:]

lux26=lux26.iloc[:460,:]
ghi26=ghi26.iloc[:460,:]


lux27=lux27.iloc[:460,:]
ghi27=ghi27.iloc[:460,:]

lux28=lux28.iloc[:459,:]
ghi28=ghi28.iloc[:459,:]

lux29=lux29.iloc[:763,:]
ghi29=ghi29.iloc[:763,:]

lux30=lux30.iloc[:460,:]
ghi30=ghi30.iloc[:460,:]

lux31=lux31.iloc[:460,:]
ghi31=ghi31.iloc[:460,:]

lux01=lux01.iloc[:460,:]
ghi01=ghi01.iloc[:460,:]

lux05=lux01.iloc[:481,:]
ghi05=ghi01.iloc[:481,:]
'''

'\n# As the rows for each day are different, we will use the minimum rows and ignore the other to avoid null values\n# checking size to match\nlux18=lux18.iloc[:737,:]\nghi18=ghi18.iloc[:737,:]\n\nlux19=lux19.iloc[:708,:]\nghi19=ghi19.iloc[:708,:]\n\nlux21=lux21.iloc[:681,:]\nghi21=ghi21.iloc[:681,:]\n\nlux22=lux22.iloc[:665,:]\nghi22=ghi22.iloc[:665,:]\n\nlux23=lux23.iloc[:606,:]\nghi23=ghi23.iloc[:606,:]\n\nlux24=lux24.iloc[:678,:]\nghi24=ghi24.iloc[:678,:]\n\nlux25=lux25.iloc[:663,:]\nghi25=ghi25.iloc[:663,:]\n\nlux26=lux26.iloc[:460,:]\nghi26=ghi26.iloc[:460,:]\n\n\nlux27=lux27.iloc[:460,:]\nghi27=ghi27.iloc[:460,:]\n\nlux28=lux28.iloc[:459,:]\nghi28=ghi28.iloc[:459,:]\n\nlux29=lux29.iloc[:763,:]\nghi29=ghi29.iloc[:763,:]\n\nlux30=lux30.iloc[:460,:]\nghi30=ghi30.iloc[:460,:]\n\nlux31=lux31.iloc[:460,:]\nghi31=ghi31.iloc[:460,:]\n\nlux01=lux01.iloc[:460,:]\nghi01=ghi01.iloc[:460,:]\n\nlux05=lux01.iloc[:481,:]\nghi05=ghi01.iloc[:481,:]\n'

# The Lux for day 18-05 are concatenated into one dataframe

In [ ]:
df_lux=pd.concat([lux18,lux19,lux21,lux22,lux23,lux24,lux25,lux26,lux27,lux28,lux29,lux30,lux31,lux01,lux05])
df_lux

,Lux0 Regression,Lux1 Regression,Lux2 Regression,Lux3 Regression,Lux4 Regression,Lux5 Regression,Lux6 Regression,Lux7 Regression,Lux8 Regression,Time
0,400,5504,5129,4641,4440,4319,4255,4250,4262,2022-12-22 08:50:15
1,400,5516,5178,4685,4485,4344,4286,4283,4296,2022-12-22 08:50:45
2,400,5562,5168,4706,4499,4356,4299,4296,4310,2022-12-22 08:51:15
3,400,5607,5151,4736,4498,4364,4313,4304,4319,2022-12-22 08:51:45
4,400,5650,5134,4694,4470,4355,4305,4296,4310,2022-12-22 08:52:15
...,...,...,...,...,...,...,...,...,...,...
476,400,3583,2388,1343,827,618,502,467,445,2023-01-05 16:09:00
477,400,3583,2388,1343,827,625,527,485,461,2023-01-05 16:10:00
478,400,3583,2388,1343,827,629,526,483,459,2023-01-05 16:11:00
479,400,3583,2388,1343,827,592,509,457,437,2023-01-05 16:12:00
480,400,3583,2388,1343,827,539,485,426,400,2023-01-05 16:13:00

# The ghi for day 18-05 are concatenated into one dataframe

In [ ]:
df_ghui=pd.concat([ghi18,ghi19,ghi21,ghi22,ghi23,ghi24,ghi25,ghi26,ghi27,ghi28,ghi29,ghi30,ghi31,ghi01,ghi05])
df_ghui

                    Time        GHI
0    2022-12-22 08:50:15  26.4 W/m²
1    2022-12-22 08:50:45  27.1 W/m²
2    2022-12-22 08:51:15  26.8 W/m²
3    2022-12-22 08:51:45  26.5 W/m²
4    2022-12-22 08:52:15  26.9 W/m²
..                   ...        ...
476  2023-01-05 16:09:00  2.88 W/m²
477  2023-01-05 16:10:00  2.57 W/m²
478  2023-01-05 16:11:00  3.11 W/m²
479  2023-01-05 16:12:00  3.02 W/m²
480  2023-01-05 16:13:00  2.81 W/m²

[8741 rows x 2 columns]

In [ ]:
df_ghui.rename(columns = {'Time':'T-Match', 'GHI':'GHI'}, inplace = True)
df_ghui

                 T-Match        GHI
0    2022-12-22 08:50:15  26.4 W/m²
1    2022-12-22 08:50:45  27.1 W/m²
2    2022-12-22 08:51:15  26.8 W/m²
3    2022-12-22 08:51:45  26.5 W/m²
4    2022-12-22 08:52:15  26.9 W/m²
..                   ...        ...
476  2023-01-05 16:09:00  2.88 W/m²
477  2023-01-05 16:10:00  2.57 W/m²
478  2023-01-05 16:11:00  3.11 W/m²
479  2023-01-05 16:12:00  3.02 W/m²
480  2023-01-05 16:13:00  2.81 W/m²

[8741 rows x 2 columns]

# The final updated dataset for Regresion model

In [ ]:
# Now concatenating 18,19,21,22,23,24,25,26,27,27,29,30,31,01, & 05 days data for both lux, ghui we will merge them
ghi_list = df_ghui['GHI'].tolist()
match_list = df_ghui['T-Match'].tolist()
df_lux['T-Match'] = match_list
df_lux['GHI'] = ghi_list

#check match
check = df_lux['Time'].equals(df_lux['T-Match'])
print(f"Time matching {check}")

df_lux

Time matching True

,Lux0 Regression,Lux1 Regression,Lux2 Regression,Lux3 Regression,Lux4 Regression,Lux5 Regression,Lux6 Regression,Lux7 Regression,Lux8 Regression,Time,T-Match,GHI
0,400,5504,5129,4641,4440,4319,4255,4250,4262,2022-12-22 08:50:15,2022-12-22 08:50:15,26.4 W/m²
1,400,5516,5178,4685,4485,4344,4286,4283,4296,2022-12-22 08:50:45,2022-12-22 08:50:45,27.1 W/m²
2,400,5562,5168,4706,4499,4356,4299,4296,4310,2022-12-22 08:51:15,2022-12-22 08:51:15,26.8 W/m²
3,400,5607,5151,4736,4498,4364,4313,4304,4319,2022-12-22 08:51:45,2022-12-22 08:51:45,26.5 W/m²
4,400,5650,5134,4694,4470,4355,4305,4296,4310,2022-12-22 08:52:15,2022-12-22 08:52:15,26.9 W/m²
...,...,...,...,...,...,...,...,...,...,...,...,...
476,400,3583,2388,1343,827,618,502,467,445,2023-01-05 16:09:00,2023-01-05 16:09:00,2.88 W/m²
477,400,3583,2388,1343,827,625,527,485,461,2023-01-05 16:10:00,2023-01-05 16:10:00,2.57 W/m²
478,400,3583,2388,1343,827,629,526,483,459,2023-01-05 16:11:00,2023-01-05 16:11:00,3.11 W/m²
479,400,3583,2388,1343,827,592,509,457,437,2023-01-05 16:12:00,2023-01-05 16:12:00,3.02 W/m²
480,400,3583,2388,1343,827,539,485,426,400,2023-01-05 16:13:00,2023-01-05 16:13:00,2.81 W/m²

In [ ]:
df_lux['Time'].equals(df_lux['T-Match'])

True

In [ ]:
df_final = df_lux.drop(['T-Match','Lux0 Regression'], axis=1)
df_final

,Lux1 Regression,Lux2 Regression,Lux3 Regression,Lux4 Regression,Lux5 Regression,Lux6 Regression,Lux7 Regression,Lux8 Regression,Time,GHI
0,5504,5129,4641,4440,4319,4255,4250,4262,2022-12-22 08:50:15,26.4 W/m²
1,5516,5178,4685,4485,4344,4286,4283,4296,2022-12-22 08:50:45,27.1 W/m²
2,5562,5168,4706,4499,4356,4299,4296,4310,2022-12-22 08:51:15,26.8 W/m²
3,5607,5151,4736,4498,4364,4313,4304,4319,2022-12-22 08:51:45,26.5 W/m²
4,5650,5134,4694,4470,4355,4305,4296,4310,2022-12-22 08:52:15,26.9 W/m²
...,...,...,...,...,...,...,...,...,...,...
476,3583,2388,1343,827,618,502,467,445,2023-01-05 16:09:00,2.88 W/m²
477,3583,2388,1343,827,625,527,485,461,2023-01-05 16:10:00,2.57 W/m²
478,3583,2388,1343,827,629,526,483,459,2023-01-05 16:11:00,3.11 W/m²
479,3583,2388,1343,827,592,509,457,437,2023-01-05 16:12:00,3.02 W/m²
480,3583,2388,1343,827,539,485,426,400,2023-01-05 16:13:00,2.81 W/m²

In [ ]:
df_final.rename(columns = {'Lux0 Regression':'Lux0', 'Lux1 Regression':'Lux1', 'Lux2 Regression':'Lux2', 'Lux3 Regression':'Lux3', 'Lux4 Regression':'Lux4', 'Lux5 Regression':'Lux5', 'Lux6 Regression':'Lux6', 'Lux7 Regression':'Lux7', 'Lux8 Regression':'Lux8',}, inplace = True)
df_final.drop_duplicates(subset=['Time'],ignore_index=True, inplace=True)
df_final

,Lux1,Lux2,Lux3,Lux4,Lux5,Lux6,Lux7,Lux8,Time,GHI
0,5504,5129,4641,4440,4319,4255,4250,4262,2022-12-22 08:50:15,26.4 W/m²
1,5516,5178,4685,4485,4344,4286,4283,4296,2022-12-22 08:50:45,27.1 W/m²
2,5562,5168,4706,4499,4356,4299,4296,4310,2022-12-22 08:51:15,26.8 W/m²
3,5607,5151,4736,4498,4364,4313,4304,4319,2022-12-22 08:51:45,26.5 W/m²
4,5650,5134,4694,4470,4355,4305,4296,4310,2022-12-22 08:52:15,26.9 W/m²
...,...,...,...,...,...,...,...,...,...,...
8071,3583,2388,1343,827,618,502,467,445,2023-01-05 16:09:00,2.88 W/m²
8072,3583,2388,1343,827,625,527,485,461,2023-01-05 16:10:00,2.57 W/m²
8073,3583,2388,1343,827,629,526,483,459,2023-01-05 16:11:00,3.11 W/m²
8074,3583,2388,1343,827,592,509,457,437,2023-01-05 16:12:00,3.02 W/m²
8075,3583,2388,1343,827,539,485,426,400,2023-01-05 16:13:00,2.81 W/m²

In [ ]:
# this is the final data set
df_final.to_csv('/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/final-ds.csv', sep=';',index=False)

In [ ]:
checking_csv=pd.read_csv('/content/drive/MyDrive/Colab/JAWAD/Updated_Model_New_Data/final-ds.csv',sep=';')
checking_csv

,Lux1,Lux2,Lux3,Lux4,Lux5,Lux6,Lux7,Lux8,Time,GHI
0,5504,5129,4641,4440,4319,4255,4250,4262,2022-12-22 08:50:15,26.4 W/m²
1,5516,5178,4685,4485,4344,4286,4283,4296,2022-12-22 08:50:45,27.1 W/m²
2,5562,5168,4706,4499,4356,4299,4296,4310,2022-12-22 08:51:15,26.8 W/m²
3,5607,5151,4736,4498,4364,4313,4304,4319,2022-12-22 08:51:45,26.5 W/m²
4,5650,5134,4694,4470,4355,4305,4296,4310,2022-12-22 08:52:15,26.9 W/m²
...,...,...,...,...,...,...,...,...,...,...
8071,3583,2388,1343,827,618,502,467,445,2023-01-05 16:09:00,2.88 W/m²
8072,3583,2388,1343,827,625,527,485,461,2023-01-05 16:10:00,2.57 W/m²
8073,3583,2388,1343,827,629,526,483,459,2023-01-05 16:11:00,3.11 W/m²
8074,3583,2388,1343,827,592,509,457,437,2023-01-05 16:12:00,3.02 W/m²
8075,3583,2388,1343,827,539,485,426,400,2023-01-05 16:13:00,2.81 W/m²

In [16]:
%%shell
jupyter nbconvert --to html /content/lux_ghi.ipynb

[NbConvertApp] Converting notebook /content/lux_ghi.ipynb to html
[NbConvertApp] Writing 380234 bytes to /content/lux_ghi.html